# Generated by Django 2.2 on 2019-04-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0002_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='discography/images', verbose_name='Обложка альбома'),
        ),
    ]
