# Generated by Django 2.2 on 2019-04-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0003_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='discography/albums/images', verbose_name='Обложка альбома'),
        ),
    ]
