# Generated by Django 2.2 on 2019-05-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0004_auto_20190430_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='text',
            field=models.TextField(default='', verbose_name='Текст песни'),
        ),
        migrations.AddField(
            model_name='song',
            name='translate',
            field=models.TextField(default='', verbose_name='Перевод песни'),
        ),
        migrations.AddField(
            model_name='song',
            name='video_url',
            field=models.URLField(default='', verbose_name='Ссылка на видео'),
        ),
    ]
