# Generated by Django 2.2 on 2019-06-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0005_auto_20190502_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(default='', max_length=300, verbose_name='Ссылка на изоражение')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.URLField(default='', max_length=300, verbose_name='Ссылка на Обложку альбома'),
        ),
    ]
